/* Run with bundled Node and NODE_PATH pointing to its node_modules. */
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({headless:true,channel:'msedge'});
  let page = await browser.newPage({viewport:{width:1280,height:1000}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8511');
  await page.getByRole('button',{name:'Start a new survey',exact:true}).click();
  // Match the component by its Streamlit name rather than depending on iframe order.
  let survey=page.frameLocator('iframe[title*="fixed_communication_survey"]');
  const participantId=(await page.getByTestId('stCode').innerText()).trim();
  assert.match(participantId,/^P-[A-F0-9]{6}$/);
  await survey.getByRole('button',{name:'Start survey',exact:true}).click();
  await survey.getByLabel('Other',{exact:true}).check();
  const other=survey.getByRole('textbox');
  await other.pressSequentially('abcd',{delay:90});
  await other.press('Backspace');
  await other.press('Control+z');
  await other.press('Control+a');
  await other.pressSequentially('friend',{delay:70});
  await survey.getByLabel('Family',{exact:true}).check();
  await survey.getByLabel('Family',{exact:true}).uncheck();
  await page.waitForTimeout(4000);
  assert.equal(await survey.locator('#save-status').isVisible(),false,'Routine save status must be hidden');
  assert.equal(await other.inputValue(),'friend');
  fs.mkdirSync('tmp/survey-qa',{recursive:true});
  await page.screenshot({path:'tmp/survey-qa/desktop.png',fullPage:true});
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Back',exact:true}).click();
  assert.equal(await survey.getByRole('textbox').inputValue(),'friend');
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Skip',exact:true}).click();
  await survey.getByLabel('Yes, I tried but stopped',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('textbox').fill('Too many errors');
  await survey.getByRole('button',{name:'Back',exact:true}).click();
  await survey.getByLabel('No, never tried',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('No',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Two hands',{exact:true}).check();
  await survey.getByLabel('I do not enter text',{exact:true}).check();
  assert.equal(await survey.getByLabel('Two hands',{exact:true}).isChecked(),false);
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  const fieldsets=survey.locator('fieldset');
  await fieldsets.nth(0).getByLabel('Other',{exact:true}).check();
  await fieldsets.nth(0).getByRole('textbox').fill('neighbour');
  await fieldsets.nth(1).getByLabel('At home',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Said it again',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Partly',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Used a different method',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  assert.equal(await survey.getByLabel('Said it again',{exact:true}).count(),0);
  await survey.getByLabel('Stopped trying to communicate the message',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('It was taking too long',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Skip',exact:true}).click();
  await survey.getByLabel('Rarely or never',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Skip',exact:true}).click();
  await survey.getByRole('button',{name:'Skip',exact:true}).click();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Change the text and show it',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Only the parts that could cause misunderstanding',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('textbox').fill('Mara Klein');
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Continue with the text as it is',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('It gets my meaning across',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  for(let i=0;i<3;i++)await survey.getByRole('button',{name:'Skip',exact:true}).click();
  await survey.getByRole('button',{name:'Continue to demonstration',exact:true}).click();
  await survey.getByLabel('No',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('textbox').fill('Nothing to add');
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(800);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'Outer page must fit mobile width');
  assert.equal(await survey.locator('body').evaluate(el=>el.scrollWidth <= innerWidth),true,'Survey must fit mobile width');
  await page.screenshot({path:'tmp/survey-qa/mobile.png',fullPage:true});
  await survey.getByRole('button',{name:'Save and take a break',exact:true}).click();
  await survey.getByText('You can now close this tab and return later using your participant ID.',{exact:true}).waitFor();
  await page.close();
  page=await browser.newPage({viewport:{width:390,height:844}});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8511');
  await page.getByRole('tab',{name:'Return to your survey',exact:true}).click();
  await page.getByRole('textbox',{name:'Participant ID',exact:true}).fill(' '+participantId.toLowerCase()+' ');
  await page.getByRole('button',{name:'Resume survey',exact:true}).click();
  survey=page.frameLocator('iframe[title*="fixed_communication_survey"]');
  await survey.getByRole('button',{name:'Continue survey',exact:true}).click();
  assert.equal(await survey.getByRole('textbox').inputValue(),'Nothing to add');
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Submit survey',exact:true}).click();
  await survey.getByText('Your responses have been saved. You can now close this tab.').waitFor();
  assert.deepEqual(errors,[]);
  const folder=path.join('.survey-preview','survey_'+participantId);
  const records=fs.readdirSync(folder).filter(f=>f.endsWith('.json')).sort().map(f=>JSON.parse(fs.readFileSync(path.join(folder,f),'utf8')));
  const final=records.at(-1), events=records.flatMap(r=>r.events);
  assert.equal(final.state.status,'submitted');
  assert.equal(final.state.answers.people.other.other,'friend');
  assert.equal(final.state.answers.asr_stopped,undefined);
  assert.equal(final.state.answers.feature_1,undefined);
  assert.equal(final.state.answers.s1_words.text,'Mara Klein');
  assert(events.some(e=>e.type==='text_input' && e.deleted==='d'));
  assert(events.some(e=>e.type==='text_input' && e.input_type==='historyUndo'));
  assert(events.some(e=>e.type==='option_deselected' && e.option==='Family'));
  assert(events.some(e=>e.type==='answer_invalidated' && e.field_id==='asr_stopped'));
  assert(events.every(e=>e.client_utc && Number.isFinite(e.elapsed_ms)));
  assert.equal(new Set(events.map(e=>e.event_id)).size,events.length);
  console.log(`PASS: full browser survey, ${records.length} saves, ${events.length} timestamped events, desktop/mobile screenshots.`);
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
