/* Run with bundled Node and NODE_PATH pointing to its node_modules. */
const {chromium} = require('playwright');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');

(async () => {
  const browser = await chromium.launch({headless:true,channel:'msedge'});
  let page = await browser.newPage({viewport:{width:1280,height:1000}});
  const errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8511');
  await page.getByRole('button',{name:'Start a new survey',exact:true}).click();
  // Match the component by its Streamlit name rather than depending on iframe order.
  let survey=page.frameLocator('iframe[title*="fixed_communication_survey"]');
  const participantId=(await page.getByTestId('stCode').innerText()).trim();
  assert.match(participantId,/^P-[A-F0-9]{6}$/);
  await survey.getByText(/Your participant ID is in the side panel on the left/).waitFor();
  assert(await page.getByTestId('stSidebar').isVisible(),'Participant ID panel open by default on desktop');
  await page.getByTestId('stSidebarCollapseButton').locator('button').click();
  await page.getByTestId('stExpandSidebarButton').waitFor();
  await page.getByTestId('stExpandSidebarButton').click();
  await page.getByTestId('stSidebarCollapseButton').locator('button').waitFor({state:'visible'});
  await survey.getByRole('button',{name:'Start survey',exact:true}).click();
  await survey.getByLabel('Other',{exact:true}).check();
  const other=survey.getByRole('textbox');
  await other.pressSequentially('abcd',{delay:90});
  await other.press('Backspace');
  await other.press('Control+z');
  await other.press('Control+a');
  await other.pressSequentially('friend',{delay:70});
  await survey.getByLabel('Family',{exact:true}).check();
  await survey.getByLabel('Family',{exact:true}).uncheck();
  await page.waitForTimeout(4000);
  assert.equal(await survey.locator('#save-status').isVisible(),false,'Routine save status must be hidden');
  assert.equal(await other.inputValue(),'friend');
  fs.mkdirSync('tmp/survey-qa',{recursive:true});
  await page.screenshot({path:'tmp/survey-qa/desktop.png',fullPage:true});
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Back',exact:true}).click();
  assert.equal(await survey.getByRole('textbox').inputValue(),'friend');
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Skip',exact:true}).click();
  // No follow-up after the speech-to-text question.
  await survey.getByLabel('Yes, I tried but stopped',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByText('Do you use an app, device, or communication board to help you communicate?').waitFor();
  // Branch change: answering the AAC follow-up, then choosing No, removes it.
  await survey.getByLabel('Yes',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('textbox').fill('Letter board');
  await survey.getByRole('button',{name:'Back',exact:true}).click();
  await survey.getByLabel('No',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Keyboard',{exact:true}).check();
  await survey.getByLabel('I do not enter text',{exact:true}).check();
  assert.equal(await survey.getByLabel('Keyboard',{exact:true}).isChecked(),false);
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  // New Part 1 question: what has made you stop trying (exclusive "I have not stopped trying").
  await survey.getByText(/what has made you stop trying to get that message across/).waitFor();
  await survey.getByLabel('It was taking too long',{exact:true}).check();
  await survey.getByLabel('I have not stopped trying',{exact:true}).check();
  assert.equal(await survey.getByLabel('It was taking too long',{exact:true}).isChecked(),false);
  await survey.getByLabel('It was too difficult or tiring',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByLabel('Rarely or never',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Skip',exact:true}).click();
  await survey.getByRole('button',{name:'Skip',exact:true}).click();
  await survey.getByText(/suppose a device could show you the words the other person understood/).waitFor();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  // Pre-demo examples have no follow-up questions: each choice goes to the next example.
  await survey.getByLabel('Change parts of the text',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByText('Example 2 — Asking for directions',{exact:true}).waitFor();
  await survey.getByLabel('Accept the text and continue the conversation',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByText('Example 3 — Talking at home',{exact:true}).waitFor();
  for(let i=0;i<3;i++)await survey.getByRole('button',{name:'Skip',exact:true}).click();
  await survey.getByRole('button',{name:'Continue to demonstration',exact:true}).click();
  await survey.getByLabel('No',{exact:true}).check();
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('textbox').fill('Nothing to add');
  await page.setViewportSize({width:390,height:844});
  await page.waitForTimeout(800);
  assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth <= innerWidth),true,'Outer page must fit mobile width');
  assert.equal(await survey.locator('body').evaluate(el=>el.scrollWidth <= innerWidth),true,'Survey must fit mobile width');
  await page.screenshot({path:'tmp/survey-qa/mobile.png',fullPage:true});
  await survey.getByRole('button',{name:'Save and take a break',exact:true}).click();
  await survey.getByText('You can now close this tab and return later using your participant ID.',{exact:true}).waitFor();
  await page.close();
  page=await browser.newPage({viewport:{width:390,height:844}});
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto('http://127.0.0.1:8511');
  await page.getByRole('tab',{name:'Return to your survey',exact:true}).click();
  await page.getByRole('textbox',{name:'Participant ID',exact:true}).fill(' '+participantId.toLowerCase()+' ');
  await page.getByRole('button',{name:'Resume survey',exact:true}).click();
  survey=page.frameLocator('iframe[title*="fixed_communication_survey"]');
  await survey.getByRole('button',{name:'Continue survey',exact:true}).click();
  assert.equal(await survey.getByRole('textbox').inputValue(),'Nothing to add');
  await survey.getByRole('button',{name:'Next',exact:true}).click();
  await survey.getByRole('button',{name:'Submit survey',exact:true}).click();
  await survey.getByText('Your responses have been saved. You can now close this tab.').waitFor();
  assert.deepEqual(errors,[]);
  const folder=path.join('.survey-preview','survey_'+participantId);
  const records=fs.readdirSync(folder).filter(f=>f.endsWith('.json')).sort().map(f=>JSON.parse(fs.readFileSync(path.join(folder,f),'utf8')));
  const final=records.at(-1), events=records.flatMap(r=>r.events);
  assert.equal(final.state.status,'submitted');
  assert.equal(final.state.answers.people.other.other,'friend');
  assert.equal(final.state.answers.aac_name,undefined);
  assert.equal(final.state.answers.asr.choices[0],'Yes, I tried but stopped');
  assert.deepEqual(final.state.answers.stop_trying.choices,['It was too difficult or tiring']);
  assert.equal(final.state.answers.story,undefined);
  assert.equal(final.state.answers.feature_1,undefined);
  assert.equal(final.state.answers.e1_edit,undefined);
  assert.equal(final.state.answers.s1_action.choices[0],'Change parts of the text');
  assert.equal(final.state.answers.s2_action.choices[0],'Accept the text and continue the conversation');
  assert(events.some(e=>e.type==='text_input' && e.deleted==='d'));
  assert(events.some(e=>e.type==='text_input' && e.input_type==='historyUndo'));
  assert(events.some(e=>e.type==='option_deselected' && e.option==='Family'));
  assert(events.some(e=>e.type==='answer_invalidated' && e.field_id==='aac_name'));
  assert(events.every(e=>e.client_utc && Number.isFinite(e.elapsed_ms)));
  assert.equal(new Set(events.map(e=>e.event_id)).size,events.length);
  console.log(`PASS: full browser survey, ${records.length} saves, ${events.length} timestamped events, desktop/mobile screenshots.`);
  await browser.close();
})().catch(e=>{console.error(e);process.exit(1);});
